name: cashnity
description: "Cashnity is your personal finance ally—an intuitive budget calculator that brings clarity, control, and confidence to your money management. Whether you're planning monthly expenses, tracking spending, or setting savings goals, Cashnity keeps you on track in real-time."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  get_cli: ^1.9.1
  get: ^4.7.2
  get_storage: ^2.1.1
  slide_to_act: ^2.0.2
  lottie: ^3.3.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/

  # optional fonts section
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
