// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9cGQCaJFDPgYhPksIbEIzkIsXzqunx0',
    appId: '1:143788809111:web:edc1df33457a256ce2c2d2',
    messagingSenderId: '143788809111',
    projectId: 'cashnity-d5a47',
    authDomain: 'cashnity-d5a47.firebaseapp.com',
    storageBucket: 'cashnity-d5a47.firebasestorage.app',
    measurementId: 'G-YHNQ89FBPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDUUkoKkIkkeDAK2FWORnQt4R5jpzce0',
    appId: '1:143788809111:android:ffa502c549dba509e2c2d2',
    messagingSenderId: '143788809111',
    projectId: 'cashnity-d5a47',
    storageBucket: 'cashnity-d5a47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkAVApSF41wbdHh9I6qZI9Ek7i2FieQQ',
    appId: '1:143788809111:ios:d7ec5959a53f52bce2c2d2',
    messagingSenderId: '143788809111',
    projectId: 'cashnity-d5a47',
    storageBucket: 'cashnity-d5a47.firebasestorage.app',
    iosBundleId: 'com.codefascia.cashnity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFkAVApSF41wbdHh9I6qZI9Ek7i2FieQQ',
    appId: '1:143788809111:ios:d7ec5959a53f52bce2c2d2',
    messagingSenderId: '143788809111',
    projectId: 'cashnity-d5a47',
    storageBucket: 'cashnity-d5a47.firebasestorage.app',
    iosBundleId: 'com.codefascia.cashnity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9cGQCaJFDPgYhPksIbEIzkIsXzqunx0',
    appId: '1:143788809111:web:31c8c7286c8a2c04e2c2d2',
    messagingSenderId: '143788809111',
    projectId: 'cashnity-d5a47',
    authDomain: 'cashnity-d5a47.firebaseapp.com',
    storageBucket: 'cashnity-d5a47.firebasestorage.app',
    measurementId: 'G-4YSXB6E5Q0',
  );
}
